/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiRouteImport } from './routes/ui'
import { Route as SemesterRouteImport } from './routes/semester'
import { Route as ResultRouteImport } from './routes/result'
import { Route as MidwayResultRouteImport } from './routes/midway-result'
import { Route as MajorRouteImport } from './routes/major'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as IndexRouteImport } from './routes/index'

const UiRoute = UiRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const SemesterRoute = SemesterRouteImport.update({
  id: '/semester',
  path: '/semester',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const MidwayResultRoute = MidwayResultRouteImport.update({
  id: '/midway-result',
  path: '/midway-result',
  getParentRoute: () => rootRouteImport,
} as any)
const MajorRoute = MajorRouteImport.update({
  id: '/major',
  path: '/major',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/intro': typeof IntroRoute
  '/major': typeof MajorRoute
  '/midway-result': typeof MidwayResultRoute
  '/result': typeof ResultRoute
  '/semester': typeof SemesterRoute
  '/ui': typeof UiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/intro': typeof IntroRoute
  '/major': typeof MajorRoute
  '/midway-result': typeof MidwayResultRoute
  '/result': typeof ResultRoute
  '/semester': typeof SemesterRoute
  '/ui': typeof UiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/intro': typeof IntroRoute
  '/major': typeof MajorRoute
  '/midway-result': typeof MidwayResultRoute
  '/result': typeof ResultRoute
  '/semester': typeof SemesterRoute
  '/ui': typeof UiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/intro'
    | '/major'
    | '/midway-result'
    | '/result'
    | '/semester'
    | '/ui'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/intro'
    | '/major'
    | '/midway-result'
    | '/result'
    | '/semester'
    | '/ui'
  id:
    | '__root__'
    | '/'
    | '/intro'
    | '/major'
    | '/midway-result'
    | '/result'
    | '/semester'
    | '/ui'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntroRoute: typeof IntroRoute
  MajorRoute: typeof MajorRoute
  MidwayResultRoute: typeof MidwayResultRoute
  ResultRoute: typeof ResultRoute
  SemesterRoute: typeof SemesterRoute
  UiRoute: typeof UiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ui': {
      id: '/ui'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof UiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semester': {
      id: '/semester'
      path: '/semester'
      fullPath: '/semester'
      preLoaderRoute: typeof SemesterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/midway-result': {
      id: '/midway-result'
      path: '/midway-result'
      fullPath: '/midway-result'
      preLoaderRoute: typeof MidwayResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/major': {
      id: '/major'
      path: '/major'
      fullPath: '/major'
      preLoaderRoute: typeof MajorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntroRoute: IntroRoute,
  MajorRoute: MajorRoute,
  MidwayResultRoute: MidwayResultRoute,
  ResultRoute: ResultRoute,
  SemesterRoute: SemesterRoute,
  UiRoute: UiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
