/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SemesterRouteImport } from './routes/semester'
import { Route as ResultRouteImport } from './routes/result'
import { Route as NextMajorVoteRouteImport } from './routes/next-major-vote'
import { Route as MidwayResultRouteImport } from './routes/midway-result'
import { Route as MajorRouteImport } from './routes/major'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MajorPreviewMajorIdRouteImport } from './routes/major-preview.$majorId'
import { Route as GameMajorIdRouteImport } from './routes/game.$majorId'

const SemesterRoute = SemesterRouteImport.update({
  id: '/semester',
  path: '/semester',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const NextMajorVoteRoute = NextMajorVoteRouteImport.update({
  id: '/next-major-vote',
  path: '/next-major-vote',
  getParentRoute: () => rootRouteImport,
} as any)
const MidwayResultRoute = MidwayResultRouteImport.update({
  id: '/midway-result',
  path: '/midway-result',
  getParentRoute: () => rootRouteImport,
} as any)
const MajorRoute = MajorRouteImport.update({
  id: '/major',
  path: '/major',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MajorPreviewMajorIdRoute = MajorPreviewMajorIdRouteImport.update({
  id: '/major-preview/$majorId',
  path: '/major-preview/$majorId',
  getParentRoute: () => rootRouteImport,
} as any)
const GameMajorIdRoute = GameMajorIdRouteImport.update({
  id: '/game/$majorId',
  path: '/game/$majorId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/intro': typeof IntroRoute
  '/major': typeof MajorRoute
  '/midway-result': typeof MidwayResultRoute
  '/next-major-vote': typeof NextMajorVoteRoute
  '/result': typeof ResultRoute
  '/semester': typeof SemesterRoute
  '/game/$majorId': typeof GameMajorIdRoute
  '/major-preview/$majorId': typeof MajorPreviewMajorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/intro': typeof IntroRoute
  '/major': typeof MajorRoute
  '/midway-result': typeof MidwayResultRoute
  '/next-major-vote': typeof NextMajorVoteRoute
  '/result': typeof ResultRoute
  '/semester': typeof SemesterRoute
  '/game/$majorId': typeof GameMajorIdRoute
  '/major-preview/$majorId': typeof MajorPreviewMajorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/intro': typeof IntroRoute
  '/major': typeof MajorRoute
  '/midway-result': typeof MidwayResultRoute
  '/next-major-vote': typeof NextMajorVoteRoute
  '/result': typeof ResultRoute
  '/semester': typeof SemesterRoute
  '/game/$majorId': typeof GameMajorIdRoute
  '/major-preview/$majorId': typeof MajorPreviewMajorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/intro'
    | '/major'
    | '/midway-result'
    | '/next-major-vote'
    | '/result'
    | '/semester'
    | '/game/$majorId'
    | '/major-preview/$majorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/intro'
    | '/major'
    | '/midway-result'
    | '/next-major-vote'
    | '/result'
    | '/semester'
    | '/game/$majorId'
    | '/major-preview/$majorId'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/intro'
    | '/major'
    | '/midway-result'
    | '/next-major-vote'
    | '/result'
    | '/semester'
    | '/game/$majorId'
    | '/major-preview/$majorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  IntroRoute: typeof IntroRoute
  MajorRoute: typeof MajorRoute
  MidwayResultRoute: typeof MidwayResultRoute
  NextMajorVoteRoute: typeof NextMajorVoteRoute
  ResultRoute: typeof ResultRoute
  SemesterRoute: typeof SemesterRoute
  GameMajorIdRoute: typeof GameMajorIdRoute
  MajorPreviewMajorIdRoute: typeof MajorPreviewMajorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/semester': {
      id: '/semester'
      path: '/semester'
      fullPath: '/semester'
      preLoaderRoute: typeof SemesterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/next-major-vote': {
      id: '/next-major-vote'
      path: '/next-major-vote'
      fullPath: '/next-major-vote'
      preLoaderRoute: typeof NextMajorVoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/midway-result': {
      id: '/midway-result'
      path: '/midway-result'
      fullPath: '/midway-result'
      preLoaderRoute: typeof MidwayResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/major': {
      id: '/major'
      path: '/major'
      fullPath: '/major'
      preLoaderRoute: typeof MajorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/major-preview/$majorId': {
      id: '/major-preview/$majorId'
      path: '/major-preview/$majorId'
      fullPath: '/major-preview/$majorId'
      preLoaderRoute: typeof MajorPreviewMajorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$majorId': {
      id: '/game/$majorId'
      path: '/game/$majorId'
      fullPath: '/game/$majorId'
      preLoaderRoute: typeof GameMajorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  IntroRoute: IntroRoute,
  MajorRoute: MajorRoute,
  MidwayResultRoute: MidwayResultRoute,
  NextMajorVoteRoute: NextMajorVoteRoute,
  ResultRoute: ResultRoute,
  SemesterRoute: SemesterRoute,
  GameMajorIdRoute: GameMajorIdRoute,
  MajorPreviewMajorIdRoute: MajorPreviewMajorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
